labels:
  gm: [3, 8, 10, 11, 12, 13, 17, 18, 26,
       42, 47, 49, 50, 51, 52, 53, 54, 62]
  wm: [2, 7, 41, 46]
  keywords_to_remove: ["Bone", "Teeth", "Cranium", "Skull", 
    "Table", "Diploe", "Endosteum", "Periosteum", "CSF", "Ventricle",
    "Humor", "Lens", "Globe", "Choroid", "Epidermis", "Scalp", "Skin",
    "Dura", "Air", "Nasal"]

files:
  flair: "FLAIR.nii"
  t1: "T1ontoFLAIR.nii"
  segmentation: "aseg.auto_noCCseg.nii"
  gm_pve: "pve_gm.nii"
  wm_pve: "pve_wm.nii"
  csf_pve: "pve_csf.nii"
  gt: "GT.nii"
  label_name: "data/FreeSurferColorLUT.txt"