labels:
  gm: [3, 42, 8, 47, 10, 49, 11, 50, 12, 51, 13, 52, 17, 53, 18, 54, 26, 58, 28, 60, 138, 139, 169, 176]
  wm: [ 2, 7, 41, 46, 77, 78, 79, 155, 156, 157,158,192]
  keywords_to_remove: ["Bone", "Teeth", "Cranium", "Skull", 
    "Table", "Diploe", "Endosteum", "Periosteum", "CSF", "Ventricle",
    "Humor", "Lens", "Globe", "Choroid", "Epidermis", "Scalp", "Skin",
    "Dura", "Air", "Nasal"]

files:
  flair: "FLAIR.nii"
  t1: "T1ontoFLAIR.nii"
  segmentation: "aseg.auto_noCCseg.nii"
  gm_pve: "pve_gm.nii"
  wm_pve: "pve_wm.nii"
  csf_pve: "pve_csf.nii"
  gt: "GT.nii"
  label_name: "FreeSurferColorLUT.txt"